projects:
  default:
    schema: 'node_modules/@shopify/hydrogen/storefront.schema.json'
    documents:
      - '!*.d.ts'
      - '*.{ts,tsx,js,jsx}'
      - 'app/**/*.{ts,tsx,js,jsx}'
      - '!app/graphql/**/*.{ts,tsx,js,jsx}'
  customer-account:
    schema: 'node_modules/@shopify/hydrogen/customer-account.schema.json'
    documents:
      - 'app/graphql/customer-account/**/*.{ts,tsx,js,jsx}'
  favorites:
    schema: '/app/graphql/favorites/favorites-schema.json'
    documents:
      - 'app/graphql/favorites/**/*.{ts,tsx,js,jsx}'

